### PR TITLE
Moderation changes

### PR DESCRIPTION
**Pull request by JasonP01**
Changed the default times and added a new one, we generally kick for long so they can get it in their heads to not grief or do whatever they did. also beg for help in trying to make overseer slightly useful 
(maybe change the set time to an hour instead, nothing over a day)

### CODE REVIEW

**Comment by JasonP01** [comment]
I literally googled to see if adding a comment was fine, it said it was, and now it failed... i hate this >:(

**Comment by phinner** [comment]
> I literally googled to see if adding a comment was fine, it said it was, and now it failed... i hate this >:(
> 
> so upon further research its cause it wants to format the code, intended to be removed anyway so failed cause its dum

That and also the fact you did not import the `minutes` time unit with `import kotlin.time.Duration.Companion.days`.
For future PRs, consider using intellij to avoid compilation issues.

I'll fix it later.

**Comment by JasonP01** [comment]
i.. didnt look at the imports, i assumed the whole time management was under 1 import since that makes the most sense, anyway ill add the import rq

**Comment by JasonP01** [comment]
that spotless apply check is stupid, why does it want a space there, it literally changes nothing, u cant even see the difference 

also im not moving that import down >:( needlessly wanty, i get there is formatting but it also doesnt need to be mean

**Comment by phinner** [comment]
> overseer cant be trusted

:rofl:

**Comment by JasonP01** [comment]
Maybe its beneficial to have spotless apply automatically run on the workflow always :/

It always wants to be useless, 2 spaces... i cant even see them

**Comment by JasonP01** [comment]
Doing stuff with this, also screw that spotless check

**Comment by JasonP01** [comment]
cant think of anything else this would need, any other changes you would do in your free time, thx for the help lol

**Comment by JasonP01** [comment]
Actually imma go add the missing cmd descriptions for discord, quite annoying for them to be missing

**Comment by JasonP01** [comment]
that was pain, but im glad its done now

whats left explain to staff how to use cmds 😢

**Comment by JasonP01** [comment]
ur a goofy ahh grammar issue

**Pull request merged**
