### PR TITLE
bundle: spanish bundle

### PR DESCRIPTION
**Pull request by JasonP01**
Spanish es

### CODE REVIEW

**Comment by phinner** [comment]
🤨 Do you even speak Spanish ?

**Comment by JasonP01** [comment]
> 🤨 Do you even speak Spanish ?

Maybe... its correct nevertheless

**Comment by phinner** [comment]
> Maybe... its correct nevertheless

I'm gonna need more than "maybe".
Do you **know** Spanish ?
I'd rather have accurate English than unverified translated Spanish.

**Comment by JasonP01** [comment]
I consulted with mindustry espanol server, they said it was translated correctly

**Comment by phinner** [comment]
Fair enough.

**Pull request merged**
