### PR TITLE
Improve the alerts feature

### PR DESCRIPTION
**Pull request by JasonP01**
Deleting the negatives of the sources isnt necessary to alert for, but filtering it is annoying

### CODE REVIEW

**Comment by JasonP01** [comment]
Bruh the errors xd

**Comment by JasonP01** [comment]
ill fix it later

**Comment by JasonP01** [comment]
Ok, last error im waiting for your response in distributor

**Comment by JasonP01** [comment]
Why workflow never runs when format code is done 🤔

**Comment by JasonP01** [comment]
In terms of the bundle conflict I declare this is a you problem, it was not conflicted when it was pr'd. I leave the burden of fixing the bundle conflict to you as i no no wanna :(

**Comment by phinner** [comment]
Partially implemented, for more kinds of alert, open an issue.

**Pull request closed without merging**
