### PR TITLE
Name-blacklist

### PR DESCRIPTION
**Pull request by JasonP01**
The WORST name blacklist in the history of history, but it should work

TODO: 
add the ability to add/remove entries from discord (so it can be updated live, without needing to update servers) `hard :(`
make some of it regex so there isnt 129124812471894 entries of different variations of the same word  `not hard for phinner/zeta :)`

### CODE REVIEW

**Comment by JasonP01** [comment]
Btw @phinner if my commits are verified to be made on discord... that means i did not test it, idk if this works, i assume it does but it also couldnt

Schrodinger's commit

**Comment by phinner** [comment]
Ok, the problem is much more complex than I thought, and a simple list of hand picked bad words and regexes won't cut it. I'll probably implement an external API for this or static list (found some but outdated).

**Comment by JasonP01** [comment]
> Ok, the problem is much more complex than I thought, and a simple list of hand picked bad words and regexes won't cut it. I'll probably implement an external API or static list (found some but outdated) for this .

the point was to let us add words to it as we see it, cause no matter what you do there will be workarounds, and other nonsense

**Comment by phinner** [comment]
> cause no matter what you do there will be workarounds, and other nonsense

Yeah, that's what I meant by had picked list

**Pull request closed without merging**
