### PR TITLE
Disconnect

### PR DESCRIPTION
**Pull request by JasonP01**
Adds a "disconnect" option to ban command

There is no afk kick, so this is a way to disconnect the player from discord, without having to pardon

### CODE REVIEW

**Comment by JasonP01** [comment]
Huh why is discord blue here

**Comment by JasonP01** [comment]
I

**Comment by JasonP01** [comment]
Agh screw it, ill just close the other one

**Comment by phinner** [comment]
It's already possible to kick someone without ban by simply using the kick button.

**Comment by JasonP01** [comment]
@phinner ye but not FROM DISCORD, and same note i cannot kick an afk flame lighter when they are afk for 3 hours in pvp

**Comment by JasonP01** [comment]
Flame lighter being the mod, which when logged in i cannot do admin actions on

**Pull request closed without merging**
