### PR TITLE
feat: implemented admin toggle

### PR DESCRIPTION
**Pull request by JasonP01**
Implemented admin toggle, toggles mods admin ingame, todo is make it so mod rank cant be votekicked, useful to catch false votekickers while remaining logged in

### CODE REVIEW

**Comment by JasonP01** [comment]
However i couldnt figure out right now how to get the rank of the target, to announce in chat.

**Comment by JasonP01** [comment]
Wtf it worked yesterday, compiled correctly and everything

**Comment by JasonP01** [comment]
I still dont understand why this is fighting me, on local it compiled and worked with no issues

**Comment by phinner** [comment]
I'm trying a experimental version od distributor, which broke he entire compilation process, I fixed it yesterday, but haven't updated this PR too.

**Comment by JasonP01** [comment]
Atleast it wasnt my fault

**Pull request merged**
