### PR TITLE
Text updates part 2

### PR DESCRIPTION
**Pull request by JasonP01**
Same shebang this time without 7 billion commits, there is more needed I just cant find the references I need (if only I had access to the old code...)

TODO can wait until i care, this pull request can be merged if you plan on updating the plugin any time soon

### CODE REVIEW

**Comment by JasonP01** [comment]
in the name of all thats spotlessKotlinCheck, there is no happy noises right now -_-

**Comment by JasonP01** [comment]
Lovely workflow 😄, does everything i need and stops that very bad check from saying the code i wrote is bad, i never asked for its opinions anyway 🙄

**Comment by JasonP01** [comment]
Ugh ill figure out the solution to issues tmr, i have solution in mind

Need to change the site area as well, work is working, doesnt help that logs code is harder to read (why did he half obfuscate it to be just confusing enough to be annoying!??)

**Comment by JasonP01** [comment]
At this point phinner, ive changed enough files to be pretty upsetty if you do anything, fixing conflicts are that annoying when 7 billion commit changes are done lol

**Comment by JasonP01** [comment]
Not even ai can help me with that 🙏 😭

**Comment by JasonP01** [comment]
@phinner at this point im done, i cant/wont do more to this pr.

All i ask of you is to answer the notes created and/or solve them (idk how to add price to the session details) and pls solve the error that i dont believe should exist, thank you. otherwise im just going to close this as its too much rn :(

**Comment by JasonP01** [comment]
all of a sudden the magical conflict that existed no longer exists, amazing

**Comment by JasonP01** [comment]
Okay so its going to forever have the builds fail now due to 85 files being wrong :-|

**Comment by phinner** [comment]
`HistoryCommand` has rendering mistake, will fix it another day.

**Comment by JasonP01** [comment]
What was wrong with the history brackets?? 
`[89][78]` is the goal, not `[[89][[78]`

**Comment by phinner** [comment]
Don't forget square brackets are used for colors. If you want to use them as they are without any issues, you need to escape them, Mindustry will automatically replace [[ with [ instead of trying to color the following text.

**Comment by phinner** [comment]
Yeah, I think I will merge this without the HistoryCommand updates. It's bound to become a separate plugin anyways.

**Comment by JasonP01** [comment]
Ok, just wanted tilelogs to look better, not too needed lol 

Wish i got logs old /e border in, it looked so cool but would need a rewrite of /e pretty much xd

**Pull request merged**
